### ISSUE TITLE
interproscan.sh can not work!!!

### ISSUE THREAD

**Issue by yuzhenpeng** [DRL/kinfin#31]
interproscan.sh -i all_proteins.faa -d out/ -dp -t p --goterms -appl SignalP-EUK-4.1,Pfam-30.0 -f TSV

Analysis Pfam-30.0 does not exist or is deactivated.
Analysis SignalP_EUK-4.1 does not exist or is deactivated.

what is wrong!!! When run the example in interproscan it was well,but above step it didn't.

There is another problem.

kinfin.py -g Orthogroups.txt -c config.txt -s SequenceIDs.txt  -p SpeciesIDs.txt -o kinfin.basic

[WARN] - PFAM-ID file 'data/Pfam-A.clans.tsv.gz' not found.

**Comment by DRL** [comment]
Hi, 

first of all, please try to work on your etiquette. Others are usually more likely to help you if you ask them nicely.  

Secondly, this is the KinFin issue section. And therefor usually not the place to discuss problems of other software, e.g. InterProScan. If you have trouble running it, you should ask for advice [here](https://github.com/ebi-pf-team/interproscan). To save you some time, it seems that the PFAM and SignalP-Euk analyses do not run, because InterProScan is not installed properly on your system.

And finally, the FTP link for the Pfam clans file has changed and automatic downloading does not work. I will fix that in the next release. In the meantime, download the Pfam file from [here](ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.clans.tsv.gz) and place it in the ```kinfin/data``` folder (but do NOT decompress the file, it looks for the ```Pfam-A.clans.tsv.gz``` file).

Please, let me know if you have any other issues with running KinFin.

All the best, 

dom

**Comment by yuzhenpeng** [comment]
Thank you very much for your answer.

Because I was very anxious to get the result and apologize for my behavior.

**Comment by DRL** [comment]
No worries.

Let me know if you run into any other issues.

cheers, 

dom

**Comment by yuzhenpeng** [comment]
The tools you developed are really great.
 
I'm still testing this tools,and I've solved the problem with interproscan. 

Look forward to your next job.
