### ISSUE TITLE
Protein | in clustering belongs to proteomes that are not present in the SpeciesClassification-file

### ISSUE THREAD

**Issue by Lamm-a** [DRL/kinfin#43]
Hi there,

Firstly thank you for this tool it is awesome!

I am reviving the following error similar to #14 and #15:
`Protein | in clustering belongs to proteomes that are not present in the SpeciesClassification-file`

The main difference is my error is singular and is referencing `|`. I assume this to be an offending character but do not know where.

My fasta sequence headers look typically like this:
`>D46_sorted | gene 1`

So I assume the pipe is causing an issue somewhere?

Any help would be appreciated :)

**Comment by DRL** [comment]
yeah, that is probably because of the headers... pipes and spaces are never good for any sort of IDs ...

I would suggest a FASTA header format like `TAXON_ID.GENE_ID`

So maybe if the taxon is C. elegans and gene ID is `gene 1`, I would do something like `CELEG.gene_1` 

Hope that helps.

cheers, 

dom
